### PR TITLE
updated product_summary_info function to latest fields returned by CMR

### PR DESCRIPTION
**Pull request by jpswinski**
It appears the product_id field is now called title.  In the list of keys to summarize, the code was throwing an exception when it tried to access the product_id.

### CODE REVIEW

**Comment by JessicaS11** [comment]
Thanks @jpswinski! Do you know if this is a uniform change across all of the CMR ICESat-2 archive? (I'll approve so that the tests run and then we'll know if we need a try/except to deal with legacy field names).

**Review by JessicaS11 — APPROVED** [review]
Approving to run tests and confirm there aren't legacy field names we'll need to handle.

**Comment by jpswinski** [comment]
> Thanks @jpswinski! Do you know if this is a uniform change across all of the CMR ICESat-2 archive? (I'll approve so that the tests run and then we'll know if we need a try/except to deal with legacy field names).

@JessicaS11 that is a good question, I am not sure.  I just ran a quick interactive test with icepyx, querying ATL03, ATL06, and ATL08.  For all three of them, the "title" field worked.  But I have not tried others.

**Comment by JessicaS11** [comment]
@jpswinski I've been having trouble getting confirmation (hence the long delay), but based on all I've seen and the interactive tests we've done, it appears to be a uniform change. I say we go ahead and merge this PR and the worst thing that happens is we need to go back to handling both in the future. Could you go ahead and merge in the latest from icepyx/development to the SlideRule branch this PR is on and then I'll merge the PR?

**Comment by jpswinski** [comment]
@JessicaS11 Sure thing!  I just merged the latest from the icepyx/development branch into the ICESat2-SlideRule/sliderule branch, so you should be go to go with the merge.

**Comment by JessicaS11** [comment]
@jpswinski ... and then somebody approved another (completely unrelated) PR so this branch is out of date with the base again. Do you know if there's a good way [as an admin] to manage/track/fix this for forks?

**Comment by jpswinski** [comment]
@JessicaS11 I don't know of a different way when using forks.  I usually use the command line, and so the GitHub interface is still a little tough for me sometimes.  I don't typically worry about updating a branch before merging it.  From a command line, what I do is I create a branch off the main branch, merge the changes into it, and then do a `git difftool --dir-diff` between the new branch and the main branch.  It tells me exactly what changes the merge will make to the code base.  If I like it, then I just do a fast forward merge on the main branch to the new one.  I'm still trying to figure out how to replicate that workflow using the GitHub UI.

**Pull request merged**
