### PR TITLE
Add __init__.py for quest module

### PR DESCRIPTION
**Pull request by weiji14**
Resolves a ModuleNotFound error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import icepyx as ipx

File ~/mambaforge/envs/hackweek/lib/python3.9/site-packages/icepyx/__init__.py:3, in <module>
      1 from icepyx.core.query import Query, GenQuery
      2 from icepyx.core.read import Read
----> 3 from icepyx.quest.quest import Quest
      5 from _icepyx_version import version as __version__

ModuleNotFoundError: No module named 'icepyx.quest'
```

### CODE REVIEW

**Comment by weiji14** [comment]
Ok hold on, I'm still getting an error, let me double check that this PR works...

**Comment by JessicaS11** [comment]
`pip install -e.` is working fine for me... are you doing a different install?

**Comment by weiji14** [comment]
Nevermind, false alarm. I just needed to restart my jupyter kernel. But all those test failures on Travis CI doesn't look good, do you know what's up with that?

**Comment by JessicaS11** [comment]
> Nevermind, false alarm. I just needed to restart my jupyter kernel. 

I think there's a meme for that. ; )

> But all those test failures on Travis CI doesn't look good, do you know what's up with that? Maybe it's because it's running on a fork rather than the main icesat2py/icepyx repo?

I had the same thought - thanks for pointing out the fork bit. The tests that failed are behind a login, so the encrypted variable can't be accessed when a fork triggers the tests (see also #272).

**Comment by weiji14** [comment]
Err, I still think we need that __init__.py file. Otherwise `import icepyx` won't work.

**Comment by JessicaS11** [comment]
Yeah. My terminal python wasn't pointing where I thought it was, so it was still working for me even after I reinstalled the newer version. I'll try and push this through and re-release later tonight.

**Review by JessicaS11 — APPROVED** [review]

**Pull request merged**
