### PR TITLE
237 increase page size

### PR DESCRIPTION
**Pull request by trey-stafford**
Looks like there are still some references to a page size of 10 in jupyter notebooks. I have not updated those, but can do so if useful!

### CODE REVIEW

**Comment by trey-stafford** [comment]
Associated issue: https://github.com/icesat2py/icepyx/issues/237

**Comment by trey-stafford** [comment]
Note that the failing test appears to be an issue on the `development` branch as well.

**Comment by JessicaS11** [comment]
@trey-stafford Thanks for this update from NSIDC! If you're able to update the notebooks to match the updated code, that would be awesome and much appreciated. I added in @weiji14's test fix (#241), so hopefully updating the base branch will fix the error.

**Comment by JessicaS11** [comment]
@trey-stafford I merged #240, so now this is out of data with the base. I also sent you an invite to the icesat2py organization so you can create a branch to submit PRs in the future and any reviewer can update from the base.

**Review by JessicaS11 — APPROVED** [review]

**Pull request merged**
