### PR TITLE
Fix continuous delivery & docs to account for setup.py -> pyproject.toml change

### PR DESCRIPTION
**Pull request by mfisher87**

### CODE REVIEW

**Comment by weiji14** [comment]
Can you also delete this line in `.coveragerc`:

https://github.com/icesat2py/icepyx/blob/38ebec9dfe01f510b45326e962df6a035d83bda6/.coveragerc#L5

**Comment by mfisher87** [comment]
:laughing: I was sure I got all of them, but forgot to include dotfiles in my grep. Thanks!

**Review by weiji14 — APPROVED** [review]
All good, thanks again!

**Comment by JessicaS11** [comment]
Thanks @weiji14 and @mfisher87!

**Pull request merged**
