### PR TITLE
Adding extra docs requirements and tweak conf

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR is my attempt in fixing the read the docs issue that's happening. I grabbed an example from https://github.com/django-auth-ldap/django-auth-ldap/blob/master/docs/conf.py

### CODE REVIEW

**Comment by weiji14** [comment]
What's the code for running the documentation build? Just wanted to test this out locally to see if it works.

**Comment by weiji14** [comment]
Can you try removing the `import icepyx` line. I don't think the `icepyx` package is used in this `conf.py` file.

**Comment by weiji14** [comment]
I noticed that readthedocs.yaml can use `method: setuptools` (see https://docs.readthedocs.io/en/stable/config-file/v2.html#python). Wonder if that might do the trick?

```diff
diff --git a/readthedocs.yml b/readthedocs.yml
index b969696..f77e621 100644
--- a/readthedocs.yml
+++ b/readthedocs.yml
@@ -22,3 +22,4 @@ python:
   install:
     - requirements: requirements-docs.txt
     - requirements: requirements.txt
+  method: setuptools
```

**Comment by lsetiawan** [comment]
> I noticed that readthedocs.yaml can use `method: setuptools` (see https://docs.readthedocs.io/en/stable/config-file/v2.html#python). Wonder if that might do the trick?
> 
> ```diff
> diff --git a/readthedocs.yml b/readthedocs.yml
> index b969696..f77e621 100644
> --- a/readthedocs.yml
> +++ b/readthedocs.yml
> @@ -22,3 +22,4 @@ python:
>    install:
>      - requirements: requirements-docs.txt
>      - requirements: requirements.txt
> +  method: setuptools
> ```

I was wondering about that. Currently it's actually doing pip install ... it's strange that doesn't work since the pypi test works and that does a pip install ...

**Comment by JessicaS11** [comment]
> > I noticed that readthedocs.yaml can use `method: setuptools` (see https://docs.readthedocs.io/en/stable/config-file/v2.html#python). Wonder if that might do the trick?
> > ```diff
> > diff --git a/readthedocs.yml b/readthedocs.yml
> > index b969696..f77e621 100644
> > --- a/readthedocs.yml
> > +++ b/readthedocs.yml
> > @@ -22,3 +22,4 @@ python:
> >    install:
> >      - requirements: requirements-docs.txt
> >      - requirements: requirements.txt
> > +  method: setuptools
> > ```
> 
> I was wondering about that. Currently it's actually doing pip install ... it's strange that doesn't work since the pypi test works and that does a pip install ...

I agree - odd indeed. I was able to get the docs to build on readthedocs by using this option (see #182). Thoughts or preferences for which approach we use?

**Comment by lsetiawan** [comment]
>I agree - odd indeed. I was able to get the docs to build on readthedocs by using this option (see #182). Thoughts or preferences for which approach we use?

Cool! If using setuptools work, then cool. That's totally fine. We can close this PR in favor of #182. @JessicaS11 Could you bring in the doc workflow to your PR? Thanks! It would be good for us to test the doc build :smile:

**Comment by JessicaS11** [comment]
> Could you bring in the doc workflow to your PR? Thanks! It would be good for us to test the doc build 😄

You and @weiji14 are on the same page (he just said the same thing in #170). I added it to #182 and am waiting for the checks to finish...

**Comment by JessicaS11** [comment]
@lsetiawan Can I delete this branch?

**Pull request closed without merging**
