### PR TITLE
Sample Notebook for ATL08

### PR DESCRIPTION
**Pull request by bidhya**
Added a sample notebook for ATL08 inside the doc folder

### CODE REVIEW

**Comment by JessicaS11** [comment]
Thanks @bidhya for this example (and apologies it's taken me so long to review your PR - I'm having trouble keeping up since the hackweek).

I'm hoping you'd be willing to make some revisions to more seamlessly integrate this example into icepyx. The notebook itself could use some more explanations to make it more beginner-friendly: what are you doing in each cell, and why? Overall, what makes your example unique or useful? I think that having quick data visualization examples is important, and this is a critical step towards that!

Another way that I think we could simplify this example would be to wrap some of the functions you have in the notebook into the icepyx code itself. Thinking about data reading/converting is already in the works and would ultimately provide a good home for that function. The gps2dyr conversion might be something we could use to expand the acceptable time inputs into an `icepyx.query` (formerly `icepyx.icesat2data`) object.

I'd be happy to work with you on making and integrating these changes!

**Comment by JessicaS11** [comment]
@bidhya I'm making my way through some of these older PRs to either incorporate them or close them. I recently used some of the code from this example (with attribution, of course) in an intro tutorial notebook I put together using ATL08 (see #202). If you're interested, we could work together to re-introduce the capabilities you have within this PR for creating a shapefile or csv. Otherwise, I will close this PR and at some point remove the branch.

**Comment by bidhya** [comment]
> @bidhya I'm making my way through some of these older PRs to either incorporate them or close them. I recently used some of the code from this example (with attribution, of course) in an intro tutorial notebook I put together using ATL08 (see #202). If you're interested, we could work together to re-introduce the capabilities you have within this PR for creating a shapefile or csv. Otherwise, I will close this PR and at some point remove the branch.

Hi @JessicaS11 I am happy to follow your lead to incorporate some of the ALT08 goodies. I think it is best to move the codes to the new notebook you have created. After that I can supplement it with additional details as we both see fit

**Comment by JessicaS11** [comment]
Closing due to inactivity.

**Pull request closed without merging**
