### PR TITLE
Add quick instructions for installing icepyx via conda

### PR DESCRIPTION
**Pull request by weiji14**
Adding 'Quickstart' and 'Using conda' subsections to the installation page so that users know how to install icepyx with the conda package manager. Also did some line wrapping of the 'Using pip' subsection and removed some whitespace.

Preview at https://icepyx--187.org.readthedocs.build/en/187/getting_started/install.html

Partially addresses #185.

### CODE REVIEW

**Comment by weiji14** [comment]
Just noticed that installation instructions are duplicated on https://github.com/icesat2py/icepyx/blob/v0.3.3/README.rst and https://github.com/icesat2py/icepyx/blob/v0.3.3/doc/source/getting_started/install.rst. Do we want to keep them both the same, or maybe have just the quickstart instructions on the main README.rst page?

**Comment by JessicaS11** [comment]
> Do we want to keep them both the same, or maybe have just the quickstart instructions on the main README.rst page?

This was done initially because the readme came before the docs. I'm open to suggestions, but I'm thinking having the quickstart + a short note about other install options with a link to the install docs page on the readme makes sense.

**Comment by weiji14** [comment]
> 
> 
> > Do we want to keep them both the same, or maybe have just the quickstart instructions on the main README.rst page?
> 
> This was done initially because the readme came before the docs. I'm open to suggestions, but I'm thinking having the quickstart + a short note about other install options with a link to the install docs page on the readme makes sense.

Ok, I've simplified the install instructions on the main README.rst page. Will leave out inserting the badges to new contributors.

**Comment by JessicaS11** [comment]
@weiji14 It turns out you don't need the space in `pip install --editable`. I quickly searched and didn't find an easy docs ref to it, but somebody shared that info with me at some point and I've been using it ever since...

**Review by kelseybisson — APPROVED** [review]

**Comment by weiji14** [comment]
> @weiji14 It turns out you don't need the space in `pip install --editable`. I quickly searched and didn't find an easy docs ref to it, but somebody shared that info with me at some point and I've been using it ever since...

Ah didn't realize that. Good to know!

**Pull request merged**
