### PR TITLE
version 1.2.0 release

### PR DESCRIPTION
**Pull request by JessicaS11**

### CODE REVIEW

**Comment by JessicaS11** [comment]
My only mild concern is #562.

**Comment by weiji14** [comment]
> My only mild concern is #562.

So technically, the TestPyPI action should be ok when triggered on release because it will be pushing a `1.2.0` tag that doesn't exist on TestPyPI yet :crossed_fingers:

**Review by weiji14 — APPROVED** [review]
:rocket:

**Comment by JessicaS11** [comment]
> So technically, the Publish to PyPI action should be ok when triggered on release because it will be pushing a 1.2.0 tag that doesn't exist on TestPyPI yet 🤞

Glad to have this confirmed (that's what I thought). I just have a penchant for ending up with the cases where what should happen isn't what happens... Thanks!

**Comment by weiji14** [comment]
> > So technically, the Publish to PyPI action should be ok when triggered on release because it will be pushing a 1.2.0 tag that doesn't exist on TestPyPI yet 🤞
> 
> Glad to have this confirmed (that's what I thought). I just have a penchant for ending up with the cases where what should happen isn't what happens... Thanks!

Yes, Murphy's law tends to come up during releases (and you and I both know how many times release dramas have happened before), so always good to check!

**Pull request merged**
