### PR TITLE
Changelog entry for v0.3.4

### PR DESCRIPTION
**Pull request by weiji14**
Making a changelog for icepyx v0.3.4 and filling in for v0.3.3 too.

Use `git log HEAD...v0.3.2 --pretty="- %s"` to get a list of changes from v0.3.2 to the current HEAD commit.

### CODE REVIEW

**Comment by JessicaS11** [comment]
Thanks, @weiji14! This looks great. I'm gonna say we wait to merge this PR until we're ready to push 0.3.4, so that we can add any other changes to the changelog!

**Comment by JessicaS11** [comment]
@weiji14 Could you add #184 to the changelog? Then I will review and merge this PR. Then I think it makes sense to release v0.3.4.

**Comment by weiji14** [comment]
> @weiji14 Could you add #184 to the changelog?

Yep, added in 324a739fcf360cf61fd1091187d8af60f3702351. I think we should 

> Then I will review and merge this PR. Then I think it makes sense to release v0.3.4.

Probably should at least mention conda installation instructions somewhere as per #185. I'll whip up a quick PR for it.

> - [ ] update the install instructions to at least mention that we're available via conda. More install instructions are needed but can come later

**Review by lsetiawan — APPROVED** [review]
LGTM :+1: Thanks!

**Pull request merged**
